version: "3.7"
services:
  mempool-web:
    restart: on-failure
    depends_on:
      - mempool-api
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-api"
    image: mempool/frontend:v2.5.0
    ports:
      - 8080:8080
    networks:
      - polar-network-1_default

  mempool-api:
    depends_on:
      - mempool-db
    environment:
      MEMPOOL_BACKEND: "none"
      MEMPOOL_NETWORK: "testnet"
      CORE_RPC_HOST: "172.17.0.1"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "mempool"
      CORE_RPC_PASSWORD: "mempool"
      DATABASE_ENABLED: 1
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: 1
    image: mempool/backend:v2.5.0
    restart: on-failure
    volumes:
      - ${HOME}/.polar/networks/1/volumes/lnd/:/lnd
    networks:
      - polar-network-1_default

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.21
    networks:
      - polar-network-1_default

networks:
  polar-network-1_default:
    external: true
